### ISSUE TITLE
CPP ? wasn't the plan in Python ?

### ISSUE THREAD

**Issue by AroraShreshth** [MagnumDingusEdu/learning-opengl#1]
Wasn't the plan to do the application in Python instead of C++ ?

Close the Issue after reading

**Comment by MagnumDingusEdu** [comment]
It was, but python is far too difficult to work in when you have to do matrix manupilation for view / projection matrices, C++ libraries are really good for that. But still, will probably port this to python someday (most of the code is still the same).
